# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '微信练习' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 微信练习

  target '微信练习Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '微信练习UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod ‘FMDB’
end
